version: '3'
services:
  influxdb:
    image: influxdb:2.6
    container_name: monitor-temp-db
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxinflux
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=monitortemp
      - DOCKER_INFLUXDB_INIT_RETENTION=5000d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    networks:
    - external-monitor-temp

networks:
  external-monitor-temp:
    external: true
